name: TimeTracker
options:
  bundleIdPrefix: com.yourname
  deploymentTarget:
    iOS: 16.0

targets:
  TimeTracker:
    type: application
    platform: iOS
    sources:
      - path: TimeTrackerSwift
        excludes:
          - "TimeTrackerSwift/TimeTrackerSwift/**"
          - "TimeTrackerSwift/ContentView.swift"
          - "TimeTrackerSwift/HistoryView.swift"
          - "TimeTrackerSwift/ActivityDetailView.swift"
    settings:
      base:
        INFOPLIST_FILE: TimeTrackerSwift/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.yourname.TimeTracker
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_TEAM: ""  # Add your development team ID here
    info:
      path: TimeTrackerSwift/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UIRequiredDeviceCapabilities: [armv7]
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
          - UIInterfaceOrientationPortraitUpsideDown
        UIBackgroundModes:
          - remote-notification
